from django.contrib import admin

# Register your models here.
from .models import *

admin.site.register(Persona)
admin.site.register(Estudiante)
admin.site.register(Nota)
admin.site.register(Observacion)
admin.site.register(RelacionAcudiente)
admin.site.register(Acudiente)
admin.site.register(AnioLectivo)
admin.site.register(Materia)
admin.site.register(PerfilUsuario)
admin.site.register(Grado)
admin.site.register(Curso)
admin.site.register(Sexo)
admin.site.register(Rol)
admin.site.register(RitmoAprendizaje)
admin.site.register(EstiloAprendizaje)
admin.site.register(NivelAprendizaje)
admin.site.register(PerfilPedagogico)
admin.site.register(Riesgo)
admin.site.register(PrediccionRiesgo)
admin.site.register(Recomendacion)
admin.site.register(PreferenciaAccesibilidad)
admin.site.register(Tema)
admin.site.register(ProgresoTema)
admin.site.register(Actividad)
admin.site.register(ActividadAsignada)
admin.site.register(AnalisisCognitivo)
admin.site.register(Carrera)
admin.site.register(RecomendacionVocacional)
admin.site.register(MaterialEstudio)
admin.site.register(MaterialAsignado)
