# Generated by Django 6.0 on 2026-01-25 20:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0003_rol_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('completada', models.BooleanField(default=False)),
                ('puntaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstiloAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NivelAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilPedagogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciaAccesibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necesita_audio', models.BooleanField(default=False)),
                ('necesita_visual', models.BooleanField(default=False)),
                ('necesita_texto_simple', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RitmoAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemaAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='asignaciondocente',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='boletin',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='observacion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='periodoacademico',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='grado',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relacionacudiente',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='asignaciondocente',
            constraint=models.UniqueConstraint(fields=('docente', 'curso', 'materia', 'anio_lectivo', 'sede'), name='unique_asignacion_docente'),
        ),
        migrations.AddConstraint(
            model_name='boletin',
            constraint=models.UniqueConstraint(fields=('estudiante', 'periodo'), name='unique_boletin_estudiante_periodo'),
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(fields=('grado', 'nombre', 'jornada'), name='unique_curso_grado_nombre_jornada'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('estudiante', 'asignacion', 'periodo'), name='unique_nota_estudiante_asignacion_periodo'),
        ),
        migrations.AddConstraint(
            model_name='observacion',
            constraint=models.UniqueConstraint(fields=('estudiante', 'asignacion', 'periodo'), name='unique_observacion_est_asig_periodo'),
        ),
        migrations.AddConstraint(
            model_name='periodoacademico',
            constraint=models.UniqueConstraint(fields=('numero', 'anio_lectivo'), name='unique_periodo_por_anio'),
        ),
        migrations.AddField(
            model_name='actividadasignada',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.actividad'),
        ),
        migrations.AddField(
            model_name='actividadasignada',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.estudiante'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.nivelaprendizaje'),
        ),
        migrations.AddField(
            model_name='perfilpedagogico',
            name='estilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.estiloaprendizaje'),
        ),
        migrations.AddField(
            model_name='perfilpedagogico',
            name='estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Principal.estudiante'),
        ),
        migrations.AddField(
            model_name='perfilpedagogico',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.nivelaprendizaje'),
        ),
        migrations.AddField(
            model_name='prediccionriesgo',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.estudiante'),
        ),
        migrations.AddField(
            model_name='preferenciaaccesibilidad',
            name='estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Principal.estudiante'),
        ),
        migrations.AddField(
            model_name='progresotema',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.nivelaprendizaje'),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.estudiante'),
        ),
        migrations.AddField(
            model_name='prediccionriesgo',
            name='riesgo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.riesgo'),
        ),
        migrations.AddField(
            model_name='perfilpedagogico',
            name='ritmo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.ritmoaprendizaje'),
        ),
        migrations.AddField(
            model_name='tema',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.materia'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.tema'),
        ),
        migrations.AddField(
            model_name='temaasignado',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.estudiante'),
        ),
        migrations.AddField(
            model_name='temaasignado',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.periodoacademico'),
        ),
        migrations.AddField(
            model_name='temaasignado',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.tema'),
        ),
        migrations.AddField(
            model_name='progresotema',
            name='tema_asignado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Principal.temaasignado'),
        ),
        migrations.AddConstraint(
            model_name='actividadasignada',
            constraint=models.UniqueConstraint(fields=('estudiante', 'actividad'), name='unique_actividad_asignada'),
        ),
        migrations.AddConstraint(
            model_name='prediccionriesgo',
            constraint=models.UniqueConstraint(fields=('estudiante', 'riesgo'), name='unique_prediccion_riesgo'),
        ),
        migrations.AddConstraint(
            model_name='tema',
            constraint=models.UniqueConstraint(fields=('materia', 'nombre'), name='unique_tema_por_materia'),
        ),
        migrations.AddConstraint(
            model_name='temaasignado',
            constraint=models.UniqueConstraint(fields=('estudiante', 'tema', 'periodo'), name='unique_tema_asignado'),
        ),
    ]
