# Generated by Django 6.0 on 2026-01-27 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0004_actividad_actividadasignada_estiloaprendizaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisCognitivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dudas_frecuentes', models.TextField()),
                ('areas_fuertes', models.TextField()),
                ('areas_debiles', models.TextField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Principal.estudiante')),
                ('nivel_general', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.nivelaprendizaje')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('activo', models.BooleanField(default=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.tema')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.estudiante')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.materialestudio')),
            ],
        ),
        migrations.CreateModel(
            name='RecomendacionVocacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibilidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('conocimientos_necesarios', models.TextField()),
                ('puntaje_requerido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.carrera')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.estudiante')),
            ],
        ),
    ]
