# Generated by Django 6.0 on 2026-01-28 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0005_carrera_analisiscognitivo_materialestudio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisiscognitivo',
            name='chat_id',
            field=models.CharField(default='migracion', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analisiscognitivo',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.estudiante'),
        ),
    ]
