# Generated by Django 6.0 on 2026-01-28 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0006_analisiscognitivo_chat_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisiscognitivo',
            name='chat_id',
        ),
        migrations.AlterField(
            model_name='analisiscognitivo',
            name='estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Principal.estudiante'),
        ),
    ]
