# Generated by Django 6.0 on 2026-01-28 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0007_remove_analisiscognitivo_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisiscognitivo',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_cognitivos', to='Principal.estudiante'),
        ),
    ]
