# Generated by Django 6.0 on 2026-01-28 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0008_alter_analisiscognitivo_estudiante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteAcudiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=10)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='actividadasignada',
            name='unique_actividad_asignada',
        ),
        migrations.RemoveConstraint(
            model_name='boletin',
            name='unique_boletin_estudiante_periodo',
        ),
        migrations.RemoveConstraint(
            model_name='nota',
            name='unique_nota_estudiante_asignacion_periodo',
        ),
        migrations.RemoveConstraint(
            model_name='observacion',
            name='unique_observacion_est_asig_periodo',
        ),
        migrations.RemoveConstraint(
            model_name='prediccionriesgo',
            name='unique_prediccion_riesgo',
        ),
        migrations.RenameField(
            model_name='observacion',
            old_name='texto',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='acudiente',
            name='relacion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='acudiente',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='materialasignado',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='recomendacion',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='recomendacionvocacional',
            name='estudiante',
        ),
        migrations.AlterField(
            model_name='analisiscognitivo',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='perfilpedagogico',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.estudiante'),
        ),
        migrations.AddConstraint(
            model_name='perfilpedagogico',
            constraint=models.UniqueConstraint(fields=('estudiante',), name='unique_perfil_fecha'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudianteacudiente',
            name='acudiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.acudiente'),
        ),
        migrations.AddField(
            model_name='estudianteacudiente',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.estudiante'),
        ),
        migrations.AddField(
            model_name='estudianteacudiente',
            name='relacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.relacionacudiente'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='anio_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.aniolectivo'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Principal.curso'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.estudiante'),
        ),
        migrations.AddField(
            model_name='actividadasignada',
            name='matricula',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Principal.matricula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boletin',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boletines', to='Principal.matricula'),
        ),
        migrations.AddField(
            model_name='materialasignado',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Principal.matricula'),
        ),
        migrations.AddField(
            model_name='nota',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Principal.matricula'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='Principal.matricula'),
        ),
        migrations.AddField(
            model_name='prediccionriesgo',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Principal.matricula'),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Principal.matricula'),
        ),
        migrations.AddField(
            model_name='recomendacionvocacional',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Principal.matricula'),
        ),
        migrations.AddConstraint(
            model_name='actividadasignada',
            constraint=models.UniqueConstraint(fields=('matricula', 'actividad'), name='unique_actividad_asignada'),
        ),
        migrations.AddConstraint(
            model_name='boletin',
            constraint=models.UniqueConstraint(fields=('matricula', 'periodo'), name='unique_boletin_matricula_periodo'),
        ),
        migrations.AddConstraint(
            model_name='materialasignado',
            constraint=models.UniqueConstraint(fields=('matricula', 'material'), name='unique_material_asignado'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('matricula', 'asignacion', 'periodo'), name='unique_nota_matricula_asignacion_periodo'),
        ),
        migrations.AddConstraint(
            model_name='observacion',
            constraint=models.UniqueConstraint(fields=('matricula', 'asignacion', 'periodo'), name='unique_observacion_matricula_asignacion_periodo'),
        ),
        migrations.AddConstraint(
            model_name='prediccionriesgo',
            constraint=models.UniqueConstraint(fields=('matricula', 'riesgo'), name='unique_prediccion_riesgo'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='conversacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Principal.conversacion'),
        ),
        migrations.RemoveField(
            model_name='actividadasignada',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='boletin',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='boletin',
            name='observaciones_generales',
        ),
        migrations.RemoveField(
            model_name='boletin',
            name='promedio_periodo',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='observacion',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='prediccionriesgo',
            name='estudiante',
        ),
        migrations.AddConstraint(
            model_name='estudianteacudiente',
            constraint=models.UniqueConstraint(fields=('estudiante', 'acudiente'), name='unique_estudiante_acudiente'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('estudiante', 'anio_lectivo'), name='unique_matricula_anual'),
        ),
    ]
