# Generated by Django 6.0 on 2026-01-28 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0009_conversacion_estudianteacudiente_matricula_mensaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='user',
        ),
        migrations.AddField(
            model_name='persona',
            name='perfil_user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='Principal.perfilusuario'),
            preserve_default=False,
        ),
    ]
